# Generated by Django 6.1 on 2026-08-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0002_alter_review_rating_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
