# Generated by Django 6.1 on 2026-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category_images/'),
        ),
    ]
