# Generated by Django 6.1 on 2026-09-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0005_alter_subcategory_sub_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
