# Generated by Django 6.1 on 2026-09-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0007_rename_subcategory_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
